<?php
/**
 * Organiser Event Count Shortcodes
 *
 * Provides per-organiser upcoming, past, and total event counts.
 *
 * Shortcodes:
 *   [spk_org_upcoming id="123"]  — upcoming events for organiser
 *   [spk_org_past     id="123"]  — past events for organiser
 *   [spk_total_events id="123"]  — total events for organiser
 *
 * `id` defaults to get_queried_object_id() so shortcodes work on
 * event-organiser single pages without an explicit attribute.
 *
 * Organiser filter:
 *   LIKE '"ID"' — matches ACF's serialized relationship storage, e.g.
 *   a:1:{i:0;s:2:"42";} — confirmed working approach from 1.1.5.
 *
 * Date filter:
 *   event_end_sort NUMERIC — Ymd integer auto-generated by class-acf-auto-fields.php.
 *   Already falls back to event_start_sort for single-day events.
 *   NOT event_end_date (d/m/Y string) — MySQL DATETIME compare against d/m/Y
 *   format is unreliable and causes inconsistent results.
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class Organiser_Event_Counts {

    const CACHE_EXPIRY = 43200; // 12 hours

    public static function register() {
        add_action( 'init', array( __CLASS__, 'init_shortcodes' ), 20 );
    }

    public static function init_shortcodes() {
        add_shortcode( 'spk_org_upcoming', array( __CLASS__, 'upcoming' ) );
        add_shortcode( 'spk_org_past',     array( __CLASS__, 'past'     ) );
        add_shortcode( 'spk_total_events', array( __CLASS__, 'total'    ) );
    }

    // -------------------------------------------------------------------------
    // Shortcode callbacks
    // -------------------------------------------------------------------------

    public static function upcoming( $atts ) {
        $atts  = self::parse_atts( $atts );
        $count = self::get_count( $atts['id'], 'upcoming' );
        return self::wrap( $count, 'org-upcoming-count', $atts['wrap'] );
    }

    public static function past( $atts ) {
        $atts  = self::parse_atts( $atts );
        $count = self::get_count( $atts['id'], 'past' );
        return self::wrap( $count, 'org-past-count', $atts['wrap'] );
    }

    public static function total( $atts ) {
        $atts  = self::parse_atts( $atts );
        $count = self::get_count( $atts['id'], 'total' );
        return self::wrap( $count, 'org-total-count', $atts['wrap'] );
    }

    // -------------------------------------------------------------------------
    // Core counting logic
    // -------------------------------------------------------------------------

    private static function get_count( $organiser_id, $type ) {
        $organiser_id = absint( $organiser_id );

        if ( ! $organiser_id ) {
            return 0;
        }

        $cache_key = 'spk_org_count_' . $organiser_id . '_' . $type;
        $cached    = get_transient( $cache_key );

        if ( $cached !== false ) {
            return (int) $cached;
        }

        $count = self::query_count( $organiser_id, $type );

        set_transient( $cache_key, $count, self::CACHE_EXPIRY );

        return $count;
    }

    /**
     * Query event count for an organiser.
     *
     * Organiser: LIKE '"ID"' matches ACF serialized relationship value (from 1.1.5).
     * Date:      event_end_sort NUMERIC — Ymd integer, reliable and consistent with
     *            the rest of the plugin. event_end_date (d/m/Y) must NOT be used
     *            for comparisons as MySQL DATETIME misparses the d/m/Y format.
     */
    private static function query_count( $organiser_id, $type ) {
        $meta_query = array(
            array(
                'key'     => 'event_organiser',
                'value'   => '"' . $organiser_id . '"',
                'compare' => 'LIKE',
            ),
        );

        if ( 'total' !== $type ) {
            $today = (int) gmdate( 'Ymd', strtotime( current_time( 'Y-m-d' ) ) );

            $meta_query[] = array(
                'key'     => 'event_end_sort',
                'value'   => $today,
                'compare' => ( 'upcoming' === $type ) ? '>=' : '<',
                'type'    => 'NUMERIC',
            );
        }

        $query = new WP_Query( array(
            'post_type'      => 'event',
            'post_status'    => 'publish',
            'posts_per_page' => -1,
            'fields'         => 'ids',
            'no_found_rows'  => false,
            'meta_query'     => $meta_query,
        ) );

        return (int) $query->found_posts;
    }

    // -------------------------------------------------------------------------
    // Cache invalidation
    // -------------------------------------------------------------------------

    public static function clear_cache_for_event( $post_id ) {
        if ( ! function_exists( 'get_field' ) ) {
            return;
        }

        $organisers = get_field( 'event_organiser', $post_id );

        if ( empty( $organisers ) || ! is_array( $organisers ) ) {
            return;
        }

        foreach ( $organisers as $org ) {
            $org_id = is_object( $org ) ? $org->ID : absint( $org );
            self::clear_cache_for_organiser( $org_id );
        }
    }

    public static function clear_cache_for_organiser( $organiser_id ) {
        $organiser_id = absint( $organiser_id );
        if ( ! $organiser_id ) {
            return;
        }

        delete_transient( 'spk_org_count_' . $organiser_id . '_upcoming' );
        delete_transient( 'spk_org_count_' . $organiser_id . '_past'     );
        delete_transient( 'spk_org_count_' . $organiser_id . '_total'    );
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private static function parse_atts( $atts ) {
        return shortcode_atts(
            array(
                'id'   => self::get_organiser_id(),
                'wrap' => 'span',
            ),
            $atts
        );
    }

    private static function get_organiser_id() {
        $path      = trim( parse_url( wp_unslash( $_SERVER['REQUEST_URI'] ), PHP_URL_PATH ), '/' );
        $parts     = explode( '/', $path );
        $org_index = array_search( 'organisers', $parts );

        if ( $org_index !== false && isset( $parts[ $org_index + 1 ] ) ) {
            $post = get_page_by_path( sanitize_title( $parts[ $org_index + 1 ] ), OBJECT, 'event-organiser' );
            if ( $post ) {
                return $post->ID;
            }
        }

        return get_queried_object_id();
    }

    private static function wrap( $count, $class, $tag = 'span' ) {
        $tag = tag_escape( $tag );
        return '<' . $tag . ' class="spk-count ' . esc_attr( $class ) . '">'
            . (int) $count
            . '</' . $tag . '>';
    }
}

Organiser_Event_Counts::register();
